/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gui;

import br.com.DAO.AdiocionarProdutoEstoqueDAO;
import br.com.modelo.AdicionarProdutoEstoque;
import javax.swing.JOptionPane;

/**
 *
 * @author Angela
 */
public class JDialogAdicionarProdutoAoEstoque extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAdicionarProdutoAoEstoque
     * @param parent
     * @param modal
     */
    public JDialogAdicionarProdutoAoEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CBPro = new javax.swing.JComboBox<>();
        jTqtd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Produto Ao Estoque");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(JBVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel1.setText("Produto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 51, -1, -1));

        CBPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBProActionPerformed(evt);
            }
        });
        getContentPane().add(CBPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 48, 241, -1));
        getContentPane().add(jTqtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 122, 70, -1));

        jLabel2.setText("Adicionar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 125, -1, -1));

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 229, -1, -1));

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JBVoltarActionPerformed

    private void CBProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBProActionPerformed

    }//GEN-LAST:event_CBProActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        AdicionarProdutoEstoque addpro = new AdicionarProdutoEstoque();
        AdiocionarProdutoEstoqueDAO adiciona = new AdiocionarProdutoEstoqueDAO();
        String cod;
        int codigo;
        cod = CBPro.getSelectedItem().toString();
        int pos = cod.indexOf("-");

        codigo = Integer.parseInt(cod.substring(0, pos));
        addpro.setCodigoProduto(codigo);
        addpro.setNome(cod.substring(pos+1));
        addpro.setQuantidade(Integer.parseInt(jTqtd.getText()));
        adiciona.salvar(addpro);
        JOptionPane.showMessageDialog(null, "Feito com sucesso!");
    }//GEN-LAST:event_jButton1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPro;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTqtd;
    // End of variables declaration//GEN-END:variables
}
